#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
RESET='\033[0m'

echo "🚨 Check if there are any uncommitted changes..."
git fetch origin && git rebase origin/main

if [ $? -eq 0 ]; then
  echo "✅ ${GREEN}No uncommitted changes${RESET}"
fi