nodeLinker: pnp
yarnPath: '.yarn/releases/yarn-berry.cjs'

packageExtensions:
  'styled-components@*':
    dependencies:
      'react-is': '^18.2.0'
  'vite-plugin-top-level-await@*':
    dependencies:
      'rollup': '*'
