services:
  db:
    container_name: ghostgres
    image: postgres:15.3-alpine
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - ghostnetwork
  server:
    container_name: ghostserver
    depends_on:
      - db
    image: server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
    networks:
      - ghostnetwork
  client:
    container_name: ghostclient
    depends_on:
      - server
    image: client
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
    networks:
      - ghostnetwork

networks:
  ghostnetwork:
    name: ghostnetwork
    driver: bridge

volumes:
  db_data:
