services:
  db:
    container_name: ghostgres
    image: postgres:15.3-alpine
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - ghostnetwork
  server:
    container_name: ghostserver
    depends_on:
      - db
    image: skdusdl8804/ghostserver
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - server_static_files:/app/backend/public
    ports:
      - 3000:3000
    networks:
      - ghostnetwork
    init: true
  client:
    container_name: ghostclient
    depends_on:
      - server
    image: skdusdl8804/ghostclient
    ports:
      - 80:80
    networks:
      - ghostnetwork

networks:
  ghostnetwork:
    name: ghostnetwork
    driver: bridge

volumes:
  db_data:
  server_static_files:
