services:
  db:
    container_name: ghostgres
    image: postgres:15.3-alpine
    restart: always
    env_file:
      - ./backend/.env.local
    volumes:
      - db_data_local:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - ghostnetwork_local
  server:
    container_name: ghostserver
    depends_on:
      - db
    image: server
    env_file:
      - ./backend/.env.local
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - server_static_files_local:/app/backend/public
    ports:
      - 3000:3000
    networks:
      - ghostnetwork_local
    init: true
  client:
    container_name: ghostclient
    depends_on:
      - server
    image: client
    build:
      context: .
      dockerfile: ./frontend/local.Dockerfile
      args:
        - VITE_BASE_URL=http://localhost:3000
        - VITE_API_URL=http://localhost:3000/api/v1
        - VITE_ASSET_URL=http://localhost:3000
    ports:
      - 5173:5173
    networks:
      - ghostnetwork_local
networks:
  ghostnetwork_local:
    name: ghostnetwork_local
    driver: bridge

volumes:
  db_data_local:
  server_static_files_local:
