services:
  server:
    container_name: ghostserver
    image: hannkim/ghostserver
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    networks:
      - ghostnetwork
    init: true
  client:
    container_name: ghostclient
    depends_on:
      - server
    image: hannkim/ghostclient
    ports:
      - 80:80
    networks:
      - ghostnetwork

networks:
  ghostnetwork:
    name: ghostnetwork
    driver: bridge
