/**
 * @description: 상수 저장 파일
 */

const FRIEND_LIMIT = 42;
const BLOCKED_USER_LIMIT = 42;
const DEFAULT_IMAGE = 'images/default_image.png';
const MESSAGE_SIZE_PER_PAGE = 32;
const MAX_IMAGE_SIZE = 4 * 1024 * 1024;
const HISTORY_SIZE_PER_PAGE = 10;
const AUTH_JWT_EXPIREIN = '15m';
const AUTH_COOKIE_EXPIREIN = 1000 * 60 * 15; // 15m
const USER_JWT_EXPIREIN = '4d';
const TWO_FACTOR_AUTH_EXPIREIN = 1000 * 60 * 5; // 5m

export {
  FRIEND_LIMIT,
  BLOCKED_USER_LIMIT,
  DEFAULT_IMAGE,
  MESSAGE_SIZE_PER_PAGE,
  MAX_IMAGE_SIZE,
  HISTORY_SIZE_PER_PAGE,
  AUTH_JWT_EXPIREIN,
  AUTH_COOKIE_EXPIREIN,
  USER_JWT_EXPIREIN,
  TWO_FACTOR_AUTH_EXPIREIN,
};
