# .github/workflows/frontend-build.yml

name: 'Frontend-Build'

on:
  pull_request:
    branches: [ develop ]
    paths: [ 'frontend/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install Dependencies
        run: cd frontend && yarn
      - name: Lint Check
        run: cd frontend && yarn lint

      - name: Typescript Compile Check
        run: cd frontend && yarn type-check

      - name: Build Check
        run: cd frontend && yarn build

      - name: Create Commit Comment
        uses: peter-evans/commit-comment@v2
        with:
          sha: ${{ github.sha }}
          body: |
            @${{ github.actor }} 다시 확인 부탁드려요!
        if: failure()
